class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    def random_word
    words = [
        "about",
        "after",
        "again",
        "air",
        "all",
        "along",
        "also",
        "an",
        "and",
        "another",
        "any",
        "are",
        "around",
        "as",
        "at",
        "away",
        "back",
        "be",
        "because",
        "been",
        "before",
        "below",
        "between",
        "both",
        "but",
        "by",
        "came",
        "can",
        "come",
        "could",
        "day",
        "did",
        "different",
        "do",
        "does",
        "don't",
        "down",
        "each",
        "end",
        "even",
        "every",
        "few",
        "find",
        "first",
        "for",
        "found",
        "from",
        ]
  words.sample
  end
end
